server_connect_timeout: 10000
listeners:
- query_port: 25577
  motd: §6§l佩可伺服器§r §bpecomc.ml§r §c✰ 1.15.2 ✰§r §a§l§n24Hr§r§a開放§r   §d§l再一次，與你相遇的物語
    - - -
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - lobby
  - main
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 60
  tab_size: 60
  force_default_server: false
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.send
  - bungeecord.command.reload
  - bungeecord.command.find
  - bungeecord.command.greload
log_pings: false
connection_throttle_limit: 40000
prevent_proxy_connections: false
timeout: 130000
server_ip: 138.19.227.116
player_limit: -1
ip_forward: true
groups:
  AI_Asada_Sinon:
  - admin
  Miyago9267:
  - admin
  SAwings:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
stats: f8f6a668-bc82-46ba-9c53-511a13c1a959
online_mode: true
forge_support: true
disabled_commands:
- disabledcommandhere
servers:
  mods:
    motd: §6§l佩可伺服器§r §bpecomc.ml§r §c✰ 1.15.2 ✰§r §a§l§n24Hr§r§a開放§r   §d§l再一次，與你相遇的物語
    address: 138.19.227.55:25562
    restricted: false
  wows:
    motd: §6§l佩可伺服器§r §bpecomc.ml§r §c✰ 1.15.2 ✰§r §a§l§n24Hr§r§a開放§r   §d§l再一次，與你相遇的物語
    address: 138.19.227.55:25564
    restricted: false
  lobby:
    motd: §6§l佩可伺服器§r §bpecomc.ml§r §c✰ 1.15.2 ✰§r §a§l§n24Hr§r§a開放§r   §d§l再一次，與你相遇的物語
    address: 138.19.227.55:25563
    restricted: false
  main:
    motd: §6§l佩可伺服器§r §bpecomc.ml§r §c✰ 1.15.2 ✰§r §a§l§n24Hr§r§a開放§r   §d§l再一次，與你相遇的物語
    address: 138.19.227.55:25566
    restricted: false
  event:
    motd: §6§l佩可伺服器§r §bpecomc.ml§r §c✰ 1.15.2 ✰§r §a§l§n24Hr§r§a開放§r   §d§l再一次，與你相遇的物語
    address: 138.19.227.55:25567
    restricted: false
  creative:
    motd: §6§l佩可伺服器§r §bpecomc.ml§r §c✰ 1.15.2 ✰§r §a§l§n24Hr§r§a開放§r   §d§l再一次，與你相遇的物語
    address: 138.19.227.55:25568
    restricted: false
  dungeon:
    motd: §6§l佩可伺服器§r §bpecomc.ml§r §c✰ 1.15.2 ✰§r §a§l§n24Hr§r§a開放§r   §d§l再一次，與你相遇的物語
    address: 138.19.227.55:25569
    restricted: false
  r:
    motd: §6§l佩可伺服器§r §bpecomc.ml§r §c✰ 1.15.2 ✰§r §a§l§n24Hr§r§a開放§r   §d§l再一次，與你相遇的物語
    address: 138.19.227.55:25570
    restricted: false
  sf4:
    motd: §6§l佩可伺服器§r §bpecomc.ml§r §c✰ 1.15.2 ✰§r §a§l§n24Hr§r§a開放§r   §d§l再一次，與你相遇的物語
    address: 138.19.227.55:25571
    restricted: false
